<a href="https://colab.research.google.com/github/bryanMontoya/machineLearning/blob/main/PCA_Conceptual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A = np.array([[2, -3, 0], [2, -5, 0], [0, 0, 3]])
print(A)

[[ 2 -3  0]
 [ 2 -5  0]
 [ 0  0  3]]


In [3]:
print(np.linalg.eig(A))

(array([ 1., -4.,  3.]), array([[0.9486833 , 0.4472136 , 0.        ],
       [0.31622777, 0.89442719, 0.        ],
       [0.        , 0.        , 1.        ]]))


In [4]:
X = np.array([[2,4,2,3,1],[1,5,6,3,4],[4,3,2,1,4],[6,5,10,2,1],[3,4,5,1,2]])
print(X)

[[ 2  4  2  3  1]
 [ 1  5  6  3  4]
 [ 4  3  2  1  4]
 [ 6  5 10  2  1]
 [ 3  4  5  1  2]]


**Paso 1: Estandarizar los datos.**

In [6]:
#Media por cada columna.
u = np.mean(X, axis = 0)
print(u)

[3.2 4.2 5.  2.  2.4]


In [7]:
#Desviación estándar por cada columna.
sigma = np.std(X, axis = 0)
print(sigma)

[1.72046505 0.74833148 2.96647939 0.89442719 1.356466  ]


In [8]:
Xz = (X-u)/sigma
print(Xz)

[[-0.69748583 -0.26726124 -1.01129979  1.11803399 -1.03209369]
 [-1.27872403  1.06904497  0.33709993  1.11803399  1.17953565]
 [ 0.46499055 -1.60356745 -1.01129979 -1.11803399  1.17953565]
 [ 1.62746694  1.06904497  1.68549966  0.         -1.03209369]
 [-0.11624764 -0.26726124  0.         -1.11803399 -0.29488391]]


**Paso 2: Construir la matriz de covarianza.**

In [10]:
Mcov = np.cov(Xz)
print(Mcov)

[[ 0.79533979  0.30364383 -0.5324668  -0.19845928 -0.36805753]
 [ 0.30364383  1.0892043  -0.37390678 -0.80303431 -0.21590704]
 [-0.5324668  -0.37390678  1.39485359 -0.62007219  0.13159218]
 [-0.19845928 -0.80303431 -0.62007219  1.36331058  0.2582552 ]
 [-0.36805753 -0.21590704  0.13159218  0.2582552   0.19411719]]


**Paso 3: Valores propios y vectores propios.**

In [12]:
l = np.linalg.eigvals(Mcov)
print(l)
lord = np.argsort(l)
print(lord)

[2.22322468e+00 2.01614545e+00 5.94970828e-01 5.64055247e-17
 2.48448413e-03]
[3 4 2 1 0]


In [14]:
l = np.flipud(np.sort(l))
print(l)
lord = np.flipud(lord)
print(lord)

[2.22322468e+00 2.01614545e+00 5.94970828e-01 2.48448413e-03
 5.64055247e-17]
[0 1 2 4 3]


**Paso 4: Variabilidad explicada.**
Cuántas características se deberían seleccionar.

In [17]:
lsum = l/np.sum(l)
print(lsum)

[4.59645424e-01 4.16832378e-01 1.23008538e-01 5.13660078e-04
 1.16616829e-17]


Se reduce el dataset de 5 características a 3 características.

In [19]:
#Suma acumulada.
print(np.cumsum(lsum))

[0.45964542 0.8764778  0.99948634 1.         1.        ]


In [22]:
Leingvals = np.linalg.eig(Mcov)
#Arroja valores propios y vectores propios.
print(Leingvals)

(array([2.22322468e+00, 2.01614545e+00, 5.94970828e-01, 5.64055247e-17,
       2.48448413e-03]), array([[-0.24117575, -0.41749763,  0.72705255, -0.4472136 ,  0.19729312],
       [-0.59126357, -0.2618256 , -0.54008054, -0.4472136 , -0.30027945],
       [-0.09967031,  0.81538434,  0.23246894, -0.4472136 , -0.26678156],
       [ 0.73798614, -0.27178917, -0.07242437, -0.4472136 , -0.41983546],
       [ 0.1941235 ,  0.13572807, -0.34701657, -0.4472136 ,  0.78960336]]))


In [27]:
#Filtrar los vectores propios.
W = Leingvals[1]
#Filtrar los 3 primeros.
W = W[:,lord[:3]]
print(W)

[[-0.24117575 -0.41749763  0.72705255]
 [-0.59126357 -0.2618256  -0.54008054]
 [-0.09967031  0.81538434  0.23246894]
 [ 0.73798614 -0.27178917 -0.07242437]
 [ 0.1941235   0.13572807 -0.34701657]]


**Paso 5: Transformar los datos originales.**

In [29]:
Z = np.dot(Xz,W)
print(Z)

[[ 1.05177502 -0.90737711 -0.32068134]
 [ 0.6967802   0.38505347 -1.91899601]
 [ 0.34066513 -0.13490983  0.64068685]
 [-1.39294082  0.27487901  1.35586353]
 [-0.69627954  0.38235446  0.24312697]]
